# Generated by Django 3.2.9 on 2021-11-13 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=2, unique=True, verbose_name='kanji')),
                ('ext_id', models.IntegerField(verbose_name='external id')),
                ('ext_key', models.IntegerField(verbose_name='external key')),
                ('strokes', models.IntegerField(verbose_name='strokes count')),
                ('jlpt', models.IntegerField(choices=[(5, 'N5'), (4, 'N4'), (3, 'N3'), (2, 'N2'), (1, 'N1')], verbose_name='jlpt level')),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(max_length=140, verbose_name='how to read')),
                ('meaning', models.TextField(blank=True, verbose_name='meaning')),
                ('kind', models.IntegerField(choices=[(1, 'Onyomi'), (2, 'Kunyomi')], verbose_name='kind')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='kanji.entity')),
            ],
        ),
    ]
