version: "3"
services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: powerkanji
      POSTGRES_PASSWORD: password
      POSTGRES_DB: powerkanji
